/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cochinodigital;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MariFer
 */
public class VisAlcancia extends javax.swing.JFrame {

    ArrayList<Moneda> Cochinito = new ArrayList<Moneda>();
    Date fecha = new Date();
    Moneda moneda;
    Alcancia alcancia;
    double total;
    String fechaTem = fecha.toString();
    String nombre;

    public VisAlcancia() {
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);

        alcancia = new Alcancia();

        //Agrupar botones
        buttonGroup.add(rBtnTOSTON);
        buttonGroup.add(rBtnUNO);
        buttonGroup.add(rBtnDOS);
        buttonGroup.add(rBtnCINCO);
        buttonGroup.add(rBtnDIES);

        BtnNuevaAlcancia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanelAlcancia = new javax.swing.JPanel();
        jLabelImageCochino = new javax.swing.JLabel();
        jPanelMonedas = new javax.swing.JPanel();
        rBtnTOSTON = new javax.swing.JRadioButton();
        rBtnUNO = new javax.swing.JRadioButton();
        rBtnDOS = new javax.swing.JRadioButton();
        rBtnCINCO = new javax.swing.JRadioButton();
        rBtnDIES = new javax.swing.JRadioButton();
        BtnAgregar = new java.awt.Button();
        jPanelRompeAlcancia = new javax.swing.JPanel();
        BtnRompeAlcancia = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jPanelSaldos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelSaldoTotal = new javax.swing.JLabel();
        BtnNuevaAlcancia = new java.awt.Button();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alcancia Virtual");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAlcancia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 119, 73)), "Alcancia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 3, 14), new java.awt.Color(211, 119, 73))); // NOI18N

        jLabelImageCochino.setBackground(new java.awt.Color(0, 204, 204));
        jLabelImageCochino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cochino.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAlcanciaLayout = new javax.swing.GroupLayout(jPanelAlcancia);
        jPanelAlcancia.setLayout(jPanelAlcanciaLayout);
        jPanelAlcanciaLayout.setHorizontalGroup(
            jPanelAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlcanciaLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelImageCochino)
                .addGap(24, 24, 24))
        );
        jPanelAlcanciaLayout.setVerticalGroup(
            jPanelAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImageCochino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAlcancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 250, 240));

        jPanelMonedas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 119, 73)), "Monedas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 3, 12), new java.awt.Color(211, 119, 73))); // NOI18N
        jPanelMonedas.setName(""); // NOI18N

        rBtnTOSTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCincuenta.png"))); // NOI18N
        rBtnTOSTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnTOSTONMouseClicked(evt);
            }
        });

        rBtnUNO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MPeso.png"))); // NOI18N
        rBtnUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnUNOActionPerformed(evt);
            }
        });

        rBtnDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDos.png"))); // NOI18N
        rBtnDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnDOSActionPerformed(evt);
            }
        });

        rBtnCINCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCinco.png"))); // NOI18N
        rBtnCINCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnCINCOActionPerformed(evt);
            }
        });

        rBtnDIES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDiez.png"))); // NOI18N
        rBtnDIES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnDIESActionPerformed(evt);
            }
        });

        BtnAgregar.setBackground(new java.awt.Color(220, 188, 156));
        BtnAgregar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        BtnAgregar.setLabel("Agregar Moneda");
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMonedasLayout = new javax.swing.GroupLayout(jPanelMonedas);
        jPanelMonedas.setLayout(jPanelMonedasLayout);
        jPanelMonedasLayout.setHorizontalGroup(
            jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonedasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rBtnTOSTON)
                .addGap(18, 18, 18)
                .addComponent(rBtnUNO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rBtnDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rBtnCINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rBtnDIES, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelMonedasLayout.setVerticalGroup(
            jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonedasLayout.createSequentialGroup()
                .addGroup(jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rBtnDOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rBtnUNO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(rBtnTOSTON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(rBtnCINCO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rBtnDIES, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMonedasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 770, 120));
        jPanelMonedas.getAccessibleContext().setAccessibleName("");

        jPanelRompeAlcancia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 119, 73)), "Romper Alcancia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 3, 14), new java.awt.Color(211, 119, 73))); // NOI18N

        BtnRompeAlcancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/martillo.png"))); // NOI18N
        BtnRompeAlcancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRompeAlcanciaActionPerformed(evt);
            }
        });

        jLabelNombre.setFont(new java.awt.Font("Kristen ITC", 3, 10)); // NOI18N
        jLabelNombre.setText("Propietarios:  Yonathan y Fernanda ");
        jLabelNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelFecha.setFont(new java.awt.Font("Kristen ITC", 3, 10)); // NOI18N
        jLabelFecha.setText("Fecha: ----/-----/-----");

        javax.swing.GroupLayout jPanelRompeAlcanciaLayout = new javax.swing.GroupLayout(jPanelRompeAlcancia);
        jPanelRompeAlcancia.setLayout(jPanelRompeAlcanciaLayout);
        jPanelRompeAlcanciaLayout.setHorizontalGroup(
            jPanelRompeAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRompeAlcanciaLayout.createSequentialGroup()
                .addGroup(jPanelRompeAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRompeAlcanciaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BtnRompeAlcancia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRompeAlcanciaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRompeAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelRompeAlcanciaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelNombre))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelRompeAlcanciaLayout.setVerticalGroup(
            jPanelRompeAlcanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRompeAlcanciaLayout.createSequentialGroup()
                .addComponent(BtnRompeAlcancia, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelRompeAlcancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 260, 240));

        jPanelSaldos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 119, 73)), "Saldos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 3, 14), new java.awt.Color(211, 119, 73))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 3, 14)); // NOI18N
        jLabel1.setText("Saldo Total:");

        jLabelSaldoTotal.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N

        javax.swing.GroupLayout jPanelSaldosLayout = new javax.swing.GroupLayout(jPanelSaldos);
        jPanelSaldos.setLayout(jPanelSaldosLayout);
        jPanelSaldosLayout.setHorizontalGroup(
            jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldosLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSaldosLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabelSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanelSaldosLayout.setVerticalGroup(
            jPanelSaldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSaldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 240, 240));

        BtnNuevaAlcancia.setBackground(new java.awt.Color(220, 188, 156));
        BtnNuevaAlcancia.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        BtnNuevaAlcancia.setLabel("Nueva Alcancia");
        BtnNuevaAlcancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNuevaAlcanciaMouseClicked(evt);
            }
        });
        getContentPane().add(BtnNuevaAlcancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 140, 40));

        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/446766.jpg"))); // NOI18N
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        total = alcancia.ContarMonedas(alcancia.AbrirDatos(), 0.0);
        jLabelSaldoTotal.setText("" + total);
        try {
            if (alcancia.AbrirFecha() == "") {
                JOptionPane.showMessageDialog(rootPane, "SE CREARA UNA ALCANCIA POR DEFECTO CON LA FECHA ACTUAL");
                nombre = JOptionPane.showInputDialog("INGRESA TU NOMBRE: ");
                jLabelNombre.setText("PROPIETARIO: " + nombre);
                jLabelFecha.setText(fechaTem);
                alcancia.GuardarFecha(fechaTem + "  " + nombre);
            } else {
                fechaTem = alcancia.AbrirFecha();
                String[] cortarString = fechaTem.split("  ");
                jLabelNombre.setText("PROPIETARIO: " + cortarString[1]);
                jLabelFecha.setText(cortarString[0]);
            }
        } catch (IOException ex) {
            Logger.getLogger(VisAlcancia.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    private void rBtnTOSTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnTOSTONMouseClicked
        rBtnTOSTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCincuenta2.png")));
        rBtnUNO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MPeso.png")));
        rBtnDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDos.png")));
        rBtnCINCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCinco.png")));
        rBtnDIES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDiez.png")));
    }//GEN-LAST:event_rBtnTOSTONMouseClicked

    private void rBtnUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnUNOActionPerformed
        rBtnTOSTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCincuenta.png")));
        rBtnUNO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MPeso2.png")));
        rBtnDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDos.png")));
        rBtnCINCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCinco.png")));
        rBtnDIES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDiez.png")));
    }//GEN-LAST:event_rBtnUNOActionPerformed

    private void rBtnDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnDOSActionPerformed
        rBtnTOSTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCincuenta.png")));
        rBtnUNO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MPeso.png")));
        rBtnDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDos2.png")));
        rBtnCINCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCinco.png")));
        rBtnDIES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDiez.png")));
    }//GEN-LAST:event_rBtnDOSActionPerformed

    private void rBtnCINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnCINCOActionPerformed
        rBtnTOSTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCincuenta.png")));
        rBtnUNO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MPeso.png")));
        rBtnDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDos.png")));
        rBtnCINCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCinco2.png")));
        rBtnDIES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDiez.png")));
    }//GEN-LAST:event_rBtnCINCOActionPerformed

    private void rBtnDIESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnDIESActionPerformed
        rBtnTOSTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCincuenta.png")));
        rBtnUNO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MPeso.png")));
        rBtnDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDos.png")));
        rBtnCINCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MCinco.png")));
        rBtnDIES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MDiez2.png")));
    }//GEN-LAST:event_rBtnDIESActionPerformed

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        MonedaSeleccionada();
        jLabelSaldoTotal.setText("" + alcancia.ContarMonedas(Cochinito, total));
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(rootPane, "EL TOTAL DE LA ALCANCIA ES DE: " + alcancia.ContarMonedas(Cochinito, total));
        alcancia.GuardarDatos(Cochinito);
    }//GEN-LAST:event_formWindowClosing

    private void BtnRompeAlcanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRompeAlcanciaActionPerformed
        int opt = JOptionPane.showConfirmDialog(rootPane, "QUIERES ROMPER LA ALCANCIA");
        if (JOptionPane.OK_OPTION == opt) {
            alcancia.RomperAlcancia();
            total = 0;
            Cochinito.clear();
            jLabelSaldoTotal.setText("" + total);
            jLabelNombre.setText("PROPIETARIO: ");
            jLabelFecha.setText("FECHA: ");
            BtnAgregar.setVisible(false);
            BtnRompeAlcancia.setVisible(false);
            BtnNuevaAlcancia.setVisible(true);
        }
    }//GEN-LAST:event_BtnRompeAlcanciaActionPerformed

    private void BtnNuevaAlcanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNuevaAlcanciaMouseClicked
        BtnAgregar.setVisible(true);
        BtnRompeAlcancia.setVisible(true);
        BtnNuevaAlcancia.setVisible(false);
        fechaTem = fecha.toString();
        nombre = JOptionPane.showInputDialog("INGRESA TU NOMBRE: ");
        jLabelNombre.setText("PROPIETARIO: " + nombre);
        jLabelFecha.setText(fechaTem);
        alcancia.GuardarFecha(fechaTem + "  " + nombre);
    }//GEN-LAST:event_BtnNuevaAlcanciaMouseClicked

    public void MonedaSeleccionada() {
        if (rBtnTOSTON.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 50 CENTAVOS");
            moneda = new Moneda(.50);
            Cochinito.add(moneda);
        }
        if (rBtnUNO.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 1 PESOS");
            moneda = new Moneda(1);
            Cochinito.add(moneda);
        }
        if (rBtnDOS.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 2 PESOS");
            moneda = new Moneda(2);
            Cochinito.add(moneda);
        }
        if (rBtnCINCO.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 5 PESOS");
            moneda = new Moneda(5);
            Cochinito.add(moneda);
        }
        if (rBtnDIES.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "AGREGASTE UNA MONEDA DE 10 PESOS");
            moneda = new Moneda(10);
            Cochinito.add(moneda);
        }
    }

    public void transparenciaBoton() {

//        BtnMCinco.setOpaque(false);
////        BtnMCinco.setContentAreaFilled(false);
//        BtnMCinco.setBorderPainted(false);
//
//        BtnMCincuenta.setOpaque(false);
////        BtnMCincuenta.setContentAreaFilled(false);
//        BtnMCincuenta.setBorderPainted(false);
//
//        BtnMDiez.setOpaque(false);
////        BtnMDiez.setContentAreaFilled(false);
//        BtnMDiez.setBorderPainted(false);
//
//        BtnMDos.setOpaque(false);
////        BtnMDos.setContentAreaFilled(false);
//        BtnMDos.setBorderPainted(false);
//
//        BtnMPeso.setOpaque(false);
////        BtnMPeso.setContentAreaFilled(false);
//        BtnMPeso.setBorderPainted(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisAlcancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisAlcancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisAlcancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisAlcancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisAlcancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BtnAgregar;
    private java.awt.Button BtnNuevaAlcancia;
    private javax.swing.JButton BtnRompeAlcancia;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelImageCochino;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSaldoTotal;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelAlcancia;
    private javax.swing.JPanel jPanelMonedas;
    private javax.swing.JPanel jPanelRompeAlcancia;
    private javax.swing.JPanel jPanelSaldos;
    private javax.swing.JRadioButton rBtnCINCO;
    private javax.swing.JRadioButton rBtnDIES;
    private javax.swing.JRadioButton rBtnDOS;
    private javax.swing.JRadioButton rBtnTOSTON;
    private javax.swing.JRadioButton rBtnUNO;
    // End of variables declaration//GEN-END:variables
}
